anydesk:
  version: '6.1.5.0'
  force: False
  password: mypassword123
  #license: ANYDESKLICENSE1234
  #source: your-repo.com
  settings:
    security:
      interactive_access: '0'
    features:
      unattended: 'true'
