anydesk:
  version: '6.1.5.0'
  force: False
  password: mypassword123
  #license: ANYDESKLICENSE1234
  #source: your-repo.com
  settings:
    security:
      # 2 allow access, 1, 0
      interactive_access: '1'
    features:
      unattended: 'true'
